name: Build and Deploy React App to GitHub Pages
on:
  pull_request:
    branches: [ main ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm install

      - name: Test
        run: npm run test

      - name: Deploy
        run: |
          git config --global user.name 'Mefix69'
          git config --global user.email 'nadyasitulina@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
          npm run deploy
